/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kit_bakery;


import java.awt.Font;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author varun
 */
public class inventory extends javax.swing.JPanel {

    /**
     * Creates new form inventory
     */
    public inventory() {
        initComponents();
        displaytable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        name_fld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        price_fld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mrp_fld = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        inventory_gif = new javax.swing.JLabel();
        inventory_png = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setPreferredSize(new java.awt.Dimension(750, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product Name", "Product Price", "Product MRP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(51, 102, 255));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 76, 390, 347));

        back_btn.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        back_btn.setText("BACK");
        back_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        back_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 90, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        name_fld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(name_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 160, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Product Name :");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, java.awt.Color.white));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Product price :");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, java.awt.Color.white));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        price_fld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        price_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_fldActionPerformed(evt);
            }
        });
        add(price_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Product MRP :");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, java.awt.Color.white));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 30));

        mrp_fld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mrp_fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrp_fldActionPerformed(evt);
            }
        });
        add(mrp_fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, 30));

        add_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        add_btn.setText("ADD");
        add_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        add(add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, 30));

        edit_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        edit_btn.setText("EDIT");
        edit_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 80, 30));

        delete_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delete_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 80, 30));

        inventory_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/inventery1.gif"))); // NOI18N
        inventory_gif.setMaximumSize(new java.awt.Dimension(161, 50));
        inventory_gif.setMinimumSize(new java.awt.Dimension(161, 50));
        inventory_gif.setPreferredSize(new java.awt.Dimension(161, 50));
        add(inventory_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 161, 50));

        inventory_png.setBackground(new java.awt.Color(255, 255, 255));
        inventory_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/inventry copy png.png"))); // NOI18N
        inventory_png.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(inventory_png, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));
    }// </editor-fold>//GEN-END:initComponents

     Connection con1;
         PreparedStatement insert;
     private void displaytable(){
             
             int c;
             
                  try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/kit_bakery","root","");
            insert = con1.prepareStatement("select * from inventory_tb");
            ResultSet rs = insert.executeQuery();
        ResultSetMetaData rss = rs.getMetaData();
        c = rss.getColumnCount();
        
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        df.setRowCount(0);
        
        while(rs.next())
        {
            Vector v2 = new Vector();
            
            for(int a=1; a<=c; a++)
            {
                v2.add(rs.getString("id"));
                 v2.add(rs.getString("ProductName"));
                  v2.add(rs.getString("ProductPrice"));
                   v2.add(rs.getString("ProductMRP"));
                
            }
            
            df.addRow(v2);
        }
        

         
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
             
  
         }
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedindex = jTable1.getSelectedRow();

        name_fld.setText(df.getValueAt(selectedindex,1).toString());
        price_fld.setText(df.getValueAt(selectedindex,2).toString());
        mrp_fld.setText(df.getValueAt(selectedindex,3).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        //add button code
        String name = name_fld.getText();
        String price = price_fld.getText();
        String mrp = mrp_fld.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/kit_bakery","root","");
            insert = con1.prepareStatement("insert into inventory_tb(ProductName,ProductPrice,ProductMRP)values(?,?,?)");
            insert.setString(1, name);
            insert.setString(2, price);
            insert.setString(3, mrp);
            insert.executeUpdate();

            //show message box code
            JOptionPane.showMessageDialog(this, "record addeddd");
            displaytable();

            name_fld.setText("");
            price_fld.setText("");
            mrp_fld.setText("");
            name_fld.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_add_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed

        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedindex = jTable1.getSelectedRow();

        try {

            int id = Integer.parseInt(df.getValueAt(selectedindex,0).toString());

            String name = name_fld.getText();
            String price = price_fld.getText();
            String mrp = mrp_fld.getText();

            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/kit_bakery","root","");
            insert = con1.prepareStatement("update inventory_tb set ProductName=?,ProductPrice =?,ProductMRP =? where id =?");
            insert.setString(1, name);
            insert.setString(2, price);
            insert.setString(3, mrp);
            insert.setInt(4, id);
            insert.executeUpdate();
            //show message box code
            JOptionPane.showMessageDialog(this, "record updateddddd");
            displaytable();

            name_fld.setText("");
            price_fld.setText("");
            mrp_fld.setText("");
            name_fld.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_edit_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed

        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedindex = jTable1.getSelectedRow();

        try {

            int id = Integer.parseInt(df.getValueAt(selectedindex,0).toString());

            int dialogResult = JOptionPane.showConfirmDialog(null, "Do You Want To Delete The Recordddd","warning",JOptionPane.YES_NO_CANCEL_OPTION);

            if(dialogResult == JOptionPane.YES_NO_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/kit_bakery","root","");
                insert = con1.prepareStatement("delete from inventory_tb where id =?");
                insert.setInt(1, id);

                insert.executeUpdate();

                //show message box code
                JOptionPane.showMessageDialog(this, "record deleteddddd");
                displaytable();

                name_fld.setText("");
                price_fld.setText("");
                mrp_fld.setText("");
                name_fld.requestFocus();

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(inventory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_delete_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
          
        kit_bakery home= new kit_bakery();
//        

        JFrame f = new JFrame();
        f.add(home);//adding button in JFrame  
 
        f.setSize(750,500);//400 width and 500 height  
//        f.setLayout(LayoutManager());//using no layout managers    
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_back_btnActionPerformed

    private void price_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_fldActionPerformed

    private void mrp_fldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrp_fldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrp_fldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JLabel inventory_gif;
    private javax.swing.JLabel inventory_png;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mrp_fld;
    private javax.swing.JTextField name_fld;
    private javax.swing.JTextField price_fld;
    // End of variables declaration//GEN-END:variables
}
