/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kit_bakery;

import javax.swing.JFrame;

/**
 *
 * @author veeramanikandan
 */
public class kit_bakery extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */

    public kit_bakery() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_home_admin = new javax.swing.JButton();
        btn_home_lgn = new javax.swing.JButton();
        btn_home_rgstr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, new java.awt.Color(204, 204, 204)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setPreferredSize(new java.awt.Dimension(750, 500));

        jPanel2.setMaximumSize(new java.awt.Dimension(750, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_home_admin.setBackground(new java.awt.Color(0, 0, 0));
        txt_home_admin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txt_home_admin.setForeground(new java.awt.Color(255, 255, 255));
        txt_home_admin.setText("ADMIN PANEL");
        txt_home_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_home_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_home_adminActionPerformed(evt);
            }
        });
        jPanel2.add(txt_home_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 161, 49));

        btn_home_lgn.setBackground(new java.awt.Color(0, 0, 0));
        btn_home_lgn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_home_lgn.setForeground(new java.awt.Color(255, 255, 255));
        btn_home_lgn.setText("LOGIN");
        btn_home_lgn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home_lgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home_lgnActionPerformed(evt);
            }
        });
        jPanel2.add(btn_home_lgn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 161, 51));

        btn_home_rgstr.setBackground(new java.awt.Color(0, 0, 0));
        btn_home_rgstr.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_home_rgstr.setForeground(new java.awt.Color(255, 255, 255));
        btn_home_rgstr.setText("REGISTER");
        btn_home_rgstr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home_rgstr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_home_rgstrActionPerformed(evt);
            }
        });
        jPanel2.add(btn_home_rgstr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 161, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/coollogo_com-45773056.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(750, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 360, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/1 copy.png"))); // NOI18N
        jLabel3.setName(""); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_home_rgstrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home_rgstrActionPerformed
        rgst_panel rgst= new rgst_panel();
//
        JFrame f = new JFrame();
        f.add(rgst);//adding button in JFrame  
// 
        f.setSize(750,500);//400 width and 500 height  
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_home_rgstrActionPerformed

    private void btn_home_lgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_home_lgnActionPerformed
        
        login_panel lg = new login_panel();
        JFrame f = new JFrame();
        f.add(lg);//adding button in JFrame  
        f.setSize(750,500);//400 width and 500 height  
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_btn_home_lgnActionPerformed

    private void txt_home_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_home_adminActionPerformed
       
        inventory inv = new inventory();
        JFrame f = new JFrame();
        f.add(inv);
        f.setSize(750, 500);//400 width and 500 height  
        f.setVisible(true); // TODO add your handling code here:
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_txt_home_adminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home_lgn;
    private javax.swing.JButton btn_home_rgstr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton txt_home_admin;
    // End of variables declaration//GEN-END:variables
}
