/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kit_bakery;

import javax.swing.JFrame;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author veeramanikandan
 */
public class login_bill extends javax.swing.JPanel {

    /**
     * Creates new form login_bill
     */
    public login_bill() {
        initComponents();
    }
      Connection con;
       PreparedStatement pst;
       DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barcode_label = new javax.swing.JLabel();
        txt_barcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_productname = new javax.swing.JTextField();
        price_label = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        qty_label = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_billing = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_print10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_bill = new javax.swing.JTextArea();
        btn_back = new javax.swing.JButton();
        btn_print1 = new javax.swing.JButton();
        btn_print2 = new javax.swing.JButton();
        login_gif = new javax.swing.JLabel();
        billing_png = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));
        setPreferredSize(new java.awt.Dimension(750, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barcode_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        barcode_label.setText("BARCODE NO.");
        add(barcode_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 110, 26));

        txt_barcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_barcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_barcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_barcodeMouseClicked(evt);
            }
        });
        txt_barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_barcodeActionPerformed(evt);
            }
        });
        txt_barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_barcodeKeyReleased(evt);
            }
        });
        add(txt_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 180, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("PRODUCT NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 120, 26));

        txt_productname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_productname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_productnameActionPerformed(evt);
            }
        });
        add(txt_productname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 180, 20));

        price_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price_label.setText("PRICE");
        add(price_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 50, 26));

        txt_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });
        add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 180, 20));

        qty_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qty_label.setText("QTY");
        add(qty_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 40, 26));

        txt_qty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_qty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });
        add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 180, 20));

        tbl_billing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tbl_billing.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbl_billing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEMS", "PRICE", "QTY", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tbl_billing);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 380, 320));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, 26));

        txt_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 116, -1));

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_add.setText("ADD");
        btn_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 60, 20));

        btn_print10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_print10.setText("PDF EXPORT");
        btn_print10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_print10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_print10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_print10MouseClicked(evt);
            }
        });
        btn_print10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print10ActionPerformed(evt);
            }
        });
        add(btn_print10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 100, 20));

        txt_bill.setColumns(20);
        txt_bill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_bill.setRows(5);
        txt_bill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txt_bill);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 340, 200));

        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_back.setText("BACK");
        btn_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 70, 20));

        btn_print1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_print1.setText("PRINT VIEW");
        btn_print1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_print1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print1ActionPerformed(evt);
            }
        });
        add(btn_print1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 100, 20));

        btn_print2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_print2.setText("PRINT VIEW");
        btn_print2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_print2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_print2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print2ActionPerformed(evt);
            }
        });
        add(btn_print2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 100, 20));

        login_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/billing_gif.gif"))); // NOI18N
        login_gif.setMaximumSize(new java.awt.Dimension(119, 62));
        login_gif.setMinimumSize(new java.awt.Dimension(119, 62));
        login_gif.setPreferredSize(new java.awt.Dimension(119, 62));
        add(login_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 119, 62));

        billing_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/billing_png.png"))); // NOI18N
        billing_png.setMaximumSize(new java.awt.Dimension(750, 500));
        billing_png.setMinimumSize(new java.awt.Dimension(750, 500));
        billing_png.setPreferredSize(new java.awt.Dimension(750, 500));
        add(billing_png, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));
    }// </editor-fold>//GEN-END:initComponents
           public void bill()
    {
        String total=txt_total.getText();
        DefaultTableModel model=new DefaultTableModel();
        model=(DefaultTableModel)tbl_billing.getModel();
        txt_bill.setText(txt_bill.getText()+"***************************************************************\n");
        txt_bill.setText(txt_bill.getText()+"                            kitbakery                \n");
        txt_bill.setFont(txt_bill.getFont().deriveFont(Font.BOLD,13f));
        txt_bill.setText(txt_bill.getText() + "*************************************************************\n");
        
        
        txt_bill.setText(txt_bill.getText()+"Product"+"\t"+"Price"+"\t"+"Qty"+"\t"+"Amount"+"\n");
        
        for(int i=0;i<model.getRowCount();i++)
        {
            String productname=(String)model.getValueAt(i,0);
            int price=(Integer)model.getValueAt(i,1);
            int qty=(Integer)model.getValueAt(i, 2);
            int amount=(Integer)model.getValueAt(i,3);
            txt_bill.setText(txt_bill.getText()+productname+"\t"+price+"\t"+qty+"\t"+amount+"\n");
        }
        txt_bill.setText(txt_bill.getText()+"\n");
        txt_bill.setText(txt_bill.getText()+"\t"+"  TotalAmount:"+total+"\n");
        txt_bill.setText(txt_bill.getText()+"\n");
        txt_bill.setText(txt_bill.getText()+"*************************************************************\n");
        txt_bill.setText(txt_bill.getText()+"             THANK YOU VISIT AGAIN               \n");
   
    }
    
    private void txt_barcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_barcodeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barcodeMouseClicked

    private void txt_barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_barcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barcodeActionPerformed

    private void txt_barcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_barcodeKeyReleased
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/kit_bakery","root","");
            String id=txt_barcode.getText();

            pst=con.prepareStatement("select id,offercode,productname,price from billing where offercode=?");
            pst.setString(1,id);
            ResultSet rs =pst.executeQuery();

            if(rs.next()==true)
            {
                String productname=rs.getString(3);
                String price=rs.getString(4);
                txt_productname.setText(productname);
                txt_price.setText(price);

            }
            else
            {
                txt_productname.setText("");
                txt_price.setText("");

            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }

    }//GEN-LAST:event_txt_barcodeKeyReleased

    private void txt_productnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_productnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_productnameActionPerformed

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceActionPerformed

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:

        String productname=(txt_productname.getText());
        int price=Integer.parseInt(txt_price.getText());
        int qty=Integer.parseInt(txt_qty.getText());
        int total=qty*price;

        model=(DefaultTableModel)tbl_billing.getModel();

        model.addRow(new Object[]
            {
                productname,
                price,
                qty,
                total
            }
        );

        int sum=0;

        for(int i=0;i<tbl_billing.getRowCount();i++)
        {
            sum = sum + Integer.parseInt(tbl_billing.getValueAt(i, 3).toString());

        }

        txt_total.setText(Integer.toString(sum));

        txt_barcode.setText("");
        txt_productname.setText("");
        txt_price.setText("");
        txt_qty.setText("");
        txt_barcode.requestFocus();

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_print10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print10ActionPerformed
        // TODO add your handling code here:

       

    }//GEN-LAST:event_btn_print10ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
      login_panel lg = new login_panel();
        JFrame f = new JFrame();
         f.add(lg);//adding button in JFrame  

        f.setSize(750,500);//400 width and 500 height  
//        f.setLayout(LayoutManager());//using no layout managers    
        f.setVisible(true);        // TODO add your handling code here:
        
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print1ActionPerformed
 bill();
        DefaultTableModel model=(DefaultTableModel)tbl_billing.getModel();
        model.setRowCount(0);
        txt_total.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_print1ActionPerformed

    private void btn_print10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_print10MouseClicked
       PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                txt_bill.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
}
        }
    }//GEN-LAST:event_btn_print10MouseClicked

    private void btn_print2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_print2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barcode_label;
    private javax.swing.JLabel billing_png;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_print1;
    private javax.swing.JButton btn_print10;
    private javax.swing.JButton btn_print2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel login_gif;
    private javax.swing.JLabel price_label;
    private javax.swing.JLabel qty_label;
    private javax.swing.JTable tbl_billing;
    private javax.swing.JTextField txt_barcode;
    private javax.swing.JTextArea txt_bill;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_productname;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
