/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kit_bakery;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*; 
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author veeramanikandan
 */
public class login_panel extends javax.swing.JPanel {


    /**
     * Creates new form login_panel
     */
    public login_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_login_uname = new javax.swing.JLabel();
        txt_login_uname = new javax.swing.JTextField();
        lbl_login_pword = new javax.swing.JLabel();
        txt_login_pword = new javax.swing.JPasswordField();
        btn_login_sbmt = new javax.swing.JButton();
        btn_login_cncl = new javax.swing.JButton();
        txt_login_1 = new javax.swing.JLabel();
        btn_login_reg = new javax.swing.JButton();
        login_gif = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        login_png = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));
        setForeground(new java.awt.Color(0, 51, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setPreferredSize(new java.awt.Dimension(750, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 8, -1, 189));

        jPanel2.setMaximumSize(new java.awt.Dimension(750, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_login_uname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_login_uname.setText(" USER NAME ");
        jPanel2.add(lbl_login_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        txt_login_uname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txt_login_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_unameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_login_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 131, -1));

        lbl_login_pword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_login_pword.setText(" PASSWORD ");
        jPanel2.add(lbl_login_pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        txt_login_pword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txt_login_pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_pwordActionPerformed(evt);
            }
        });
        jPanel2.add(txt_login_pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 129, -1));

        btn_login_sbmt.setText("SUBMIT");
        btn_login_sbmt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_login_sbmt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login_sbmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_sbmtActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login_sbmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 66, -1));

        btn_login_cncl.setText("CANCEL");
        btn_login_cncl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_login_cncl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login_cncl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_cnclActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login_cncl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 66, -1));

        txt_login_1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txt_login_1.setText("New to KIT Bakery ?");
        jPanel2.add(txt_login_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        btn_login_reg.setBackground(new java.awt.Color(0, 204, 204));
        btn_login_reg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_login_reg.setText("REGISTER NOW...!!!");
        btn_login_reg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_login_reg.setBorderPainted(false);
        btn_login_reg.setContentAreaFilled(false);
        btn_login_reg.setFocusPainted(false);
        btn_login_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_regActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 120, 30));

        login_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/login_gif_1.gif"))); // NOI18N
        jPanel2.add(login_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 93, 81));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/login_title_gif.gif"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 268, 81));

        login_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/login_png.png"))); // NOI18N
        jPanel2.add(login_png, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));
    }// </editor-fold>//GEN-END:initComponents
Connection con;
PreparedStatement pst;
ResultSet rs;

    private void txt_login_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_unameActionPerformed

    private void btn_login_sbmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_sbmtActionPerformed
    String userid = txt_login_uname.getText();
    String pwd    = txt_login_pword.getText();

   try {
        Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kit_bakery", "root", ""); 
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM cusreg");
            
            
                Boolean b=false;

        while(rs.next()) {
        if(rs.getString("userid").equals(userid) && rs.getString("pwd").equals(pwd)){
            b=true;
        }
        }
            if(b){
            JFrame frame = new JFrame("Swing Tester");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(frame, "Successfully Login");
            login_bill lgnbill = new login_bill();
            JFrame f = new JFrame();
            f.add(lgnbill);//adding button in JFrame  
            f.setSize(750, 500);//400 width and 500 height  
            f.setVisible(true);
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            b=true;  
          }
            else {
            JFrame frame = new JFrame("Swing Tester");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(frame, "Login Failed");
            }
//            System.out.println(userid);
//            System.out.println(pwd);
//            System.out.println(rs.getString("userid"));
//            System.out.println(rs.getString("pwd"));
          
    }
    catch (Exception e) {
        System.out.println("SQL Exception: "+ e.toString());
    }
    try{
         Statement stmt=con.createStatement();  
     ResultSet rs=stmt.executeQuery("select * from emp");  
     if(!rs.next()){
     }else{
     }
        }catch(Exception e){
    }
   
     
    
    }//GEN-LAST:event_btn_login_sbmtActionPerformed

    private void btn_login_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_regActionPerformed
        rgst_panel rgst= new rgst_panel();
//
        JFrame f = new JFrame();
        f.add(rgst);//adding button in JFrame  
// 
        f.setSize(750,500);//400 width and 500 height  
        f.setVisible(true);        // TODO add your handling code here:
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_login_regActionPerformed

    private void btn_login_cnclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_cnclActionPerformed
        
        kit_bakery home= new kit_bakery();
//        

        JFrame f = new JFrame();
        f.add(home);//adding button in JFrame  
 
        f.setSize(750,500);//400 width and 500 height  
//        f.setLayout(LayoutManager());//using no layout managers    
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_login_cnclActionPerformed

    private void txt_login_pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_pwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_pwordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login_cncl;
    private javax.swing.JButton btn_login_reg;
    private javax.swing.JButton btn_login_sbmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_login_pword;
    private javax.swing.JLabel lbl_login_uname;
    private javax.swing.JLabel login_gif;
    private javax.swing.JLabel login_png;
    private javax.swing.JLabel txt_login_1;
    private javax.swing.JPasswordField txt_login_pword;
    private javax.swing.JTextField txt_login_uname;
    // End of variables declaration//GEN-END:variables
}
