/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kit_bakery;
import java.sql.*;  
import javax.swing.JFrame;
import java.math.BigInteger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author veeramanikandan
 */
public class rgst_panel extends javax.swing.JPanel {

    /**
     * Creates new form rgst_panel
     */
    public rgst_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        txt_rgst_name = new javax.swing.JTextField();
        lbl_reg_name = new javax.swing.JLabel();
        txt_rgst_uid = new javax.swing.JTextField();
        lbl_reg_uname = new javax.swing.JLabel();
        txt_rgst_mobile = new javax.swing.JTextField();
        lbl_reg_mno = new javax.swing.JLabel();
        txt_rgst_mail = new javax.swing.JTextField();
        lbl_reg_mid = new javax.swing.JLabel();
        txt_rgst_pwd = new javax.swing.JTextField();
        lbl_reg_pwd = new javax.swing.JLabel();
        txt_rgst_cpwd = new javax.swing.JTextField();
        lbl_reg_cpwd = new javax.swing.JLabel();
        btn_reg_cancel = new javax.swing.JButton();
        btn_reg_submit = new javax.swing.JButton();
        rigester_gif = new javax.swing.JLabel();
        rigester_title_gif = new javax.swing.JLabel();
        rigester_png = new javax.swing.JLabel();

        jTextField7.setText("jTextField7");

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        setMaximumSize(new java.awt.Dimension(750, 500));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setPreferredSize(new java.awt.Dimension(750, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_rgst_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txt_rgst_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rgst_nameActionPerformed(evt);
            }
        });
        add(txt_rgst_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 160, 30));

        lbl_reg_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_reg_name.setText("NAME");
        add(lbl_reg_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        txt_rgst_uid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txt_rgst_uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rgst_uidActionPerformed(evt);
            }
        });
        add(txt_rgst_uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 160, 30));

        lbl_reg_uname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_reg_uname.setText("USER ID ");
        add(lbl_reg_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 122, -1));

        txt_rgst_mobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txt_rgst_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rgst_mobileActionPerformed(evt);
            }
        });
        add(txt_rgst_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 160, 30));

        lbl_reg_mno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_reg_mno.setText("MOBILE NUMBER");
        add(lbl_reg_mno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        txt_rgst_mail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txt_rgst_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rgst_mailActionPerformed(evt);
            }
        });
        add(txt_rgst_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, 30));

        lbl_reg_mid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_reg_mid.setText("MAIL ID");
        add(lbl_reg_mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        txt_rgst_pwd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txt_rgst_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rgst_pwdActionPerformed(evt);
            }
        });
        add(txt_rgst_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 160, 30));

        lbl_reg_pwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_reg_pwd.setText("PASSWORD");
        add(lbl_reg_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        txt_rgst_cpwd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txt_rgst_cpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rgst_cpwdActionPerformed(evt);
            }
        });
        add(txt_rgst_cpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 160, 30));

        lbl_reg_cpwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_reg_cpwd.setText("RE-ENTER PASSWORD");
        add(lbl_reg_cpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        btn_reg_cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reg_cancel.setText("CANCEL");
        btn_reg_cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_reg_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reg_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg_cancelActionPerformed(evt);
            }
        });
        add(btn_reg_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 70, 30));

        btn_reg_submit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reg_submit.setText("SUBMIT");
        btn_reg_submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btn_reg_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reg_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg_submitActionPerformed(evt);
            }
        });
        add(btn_reg_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 80, 30));

        rigester_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/registergif.gif"))); // NOI18N
        rigester_gif.setText("rigestet");
        rigester_gif.setMaximumSize(new java.awt.Dimension(139, 81));
        rigester_gif.setMinimumSize(new java.awt.Dimension(139, 81));
        rigester_gif.setPreferredSize(new java.awt.Dimension(139, 81));
        add(rigester_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 139, 60));

        rigester_title_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/registertitlegif.gif"))); // NOI18N
        add(rigester_title_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 268, 60));

        rigester_png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kit_bakery/pic/registercopy.png"))); // NOI18N
        add(rigester_png, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rgst_uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rgst_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rgst_uidActionPerformed

    private void btn_reg_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg_cancelActionPerformed

        kit_bakery home = new kit_bakery();
//        

        JFrame f = new JFrame();
        f.add(home);//adding button in JFrame  

        f.setSize(750, 500);//400 width and 500 height  
//        f.setLayout(LayoutManager());//using no layout managers    
        f.setVisible(true);
        // TODO add your handling code here:
        
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_reg_cancelActionPerformed

    private void btn_reg_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg_submitActionPerformed

        String name = txt_rgst_name.getText();
        String uid = txt_rgst_uid.getText();
        String pwd = txt_rgst_pwd.getText();
        String mobile = txt_rgst_mobile.getText();
        String mail = txt_rgst_mail.getText();
        String cpwd = txt_rgst_cpwd.getText();
        
        if(name.isEmpty() || uid.isEmpty()||pwd.isEmpty() || mobile.isEmpty() || mail.isEmpty() || cpwd.isEmpty()){
            JFrame frame = new JFrame("Swing Tester");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(frame, "Fill Up All The Field");
        }else if(!pwd.equals(cpwd)){
            JFrame frame = new JFrame("Swing Tester");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(frame, "Password and Conform Password Des Not Match");
        }else{
            
            try {
            Class.forName("com.mysql.jdbc.Driver");
           
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/kit_bakery", "root", ""); 
            Statement stmt = con.createStatement();
            BigInteger mob = new BigInteger(mobile);
            String cmdString ="INSERT INTO cusreg (name, userid, mailid, moblie, pwd, cpwd) VALUES ('"+name+"', '"+uid+"','"+mail+"','"+mob+"','"+pwd+"','"+cpwd+"')";
//            int rs = stmt.executeUpdate("INSERT INTO cusreg (name, userid, mailid, moblie, pwd, cpwd) VALUES ('Rajesh', 'rajesh123', 'rajesh123@gmail.com', '9898989898', '1234', '1234')");
            int rs = stmt.executeUpdate(cmdString);
            
            con.close();
            
            txt_rgst_cpwd.setText("");
            txt_rgst_name.setText("");
            txt_rgst_mail.setText("");
            txt_rgst_mobile.setText("");
            txt_rgst_pwd.setText("");
            txt_rgst_uid.setText("");
            JFrame frame = new JFrame("Swing Tester");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JOptionPane.showMessageDialog(frame, "Successfully Registered... Please Login");
            
                  kit_bakery home = new kit_bakery();
        JFrame f = new JFrame();
         f.add(home);//adding button in JFrame  

        f.setSize(750,500);  
//        f.setLayout(LayoutManager());//using no layout managers    
        f.setVisible(true);
            
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        } catch (Exception e) {
            System.out.println(e);

        }
        }
        
                // TODO add your handling code here:
    }//GEN-LAST:event_btn_reg_submitActionPerformed

    private void txt_rgst_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rgst_nameActionPerformed
        
    }//GEN-LAST:event_txt_rgst_nameActionPerformed

    private void txt_rgst_cpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rgst_cpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rgst_cpwdActionPerformed

    private void txt_rgst_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rgst_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rgst_pwdActionPerformed

    private void txt_rgst_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rgst_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rgst_mailActionPerformed

    private void txt_rgst_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rgst_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rgst_mobileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reg_cancel;
    private javax.swing.JButton btn_reg_submit;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lbl_reg_cpwd;
    private javax.swing.JLabel lbl_reg_mid;
    private javax.swing.JLabel lbl_reg_mno;
    private javax.swing.JLabel lbl_reg_name;
    private javax.swing.JLabel lbl_reg_pwd;
    private javax.swing.JLabel lbl_reg_uname;
    private javax.swing.JLabel rigester_gif;
    private javax.swing.JLabel rigester_png;
    private javax.swing.JLabel rigester_title_gif;
    private javax.swing.JTextField txt_rgst_cpwd;
    private javax.swing.JTextField txt_rgst_mail;
    private javax.swing.JTextField txt_rgst_mobile;
    private javax.swing.JTextField txt_rgst_name;
    private javax.swing.JTextField txt_rgst_pwd;
    private javax.swing.JTextField txt_rgst_uid;
    // End of variables declaration//GEN-END:variables
}
